#!/bin/sh

# config
PEDE_DIRECTORY=$HOME/code/pede # pede and power.icon should both live here.
WALLPAPER=$HOME/Pictures/wallpaper.png
export GTK_THEME=Cloak-3.22
export GTK_MODULES=canberra-gtk-module

# not config
export GTK2_RC_FILES=/usr/share/themes/$GTK_THEME/gtk-2.0/gtkrc
export GTK_IM_MODULE=xim
export QT_IM_MODULE=xim
export XMODIFIERS=@im=ibus
export XAUTHORITY=$HOME/.Xauthority

# make sure new processes start somewhere sensible
pushd $HOME

# configure X itself
/usr/bin/hsetroot -center $WALLPAPER &
/usr/bin/xsetroot -cursor_name arrow &
/usr/bin/xset -dpms s off &

# start some daemons
/usr/bin/xcompmgr -cfr 16 -D2 &
/usr/bin/xscreensaver &
POLKIT="/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1"
test -x "$POLKIT" && "$POLKIT" &
/usr/bin/start-pulseaudio-x11 &
/usr/bin/ibus-daemon --xim &
/usr/bin/numlockx &
/usr/bin/xbanish &

# start pede
rm $PEDE_DIRECTORY/stopping$DISPLAY
touch $PEDE_DIRECTORY/starting$DISPLAY
$PEDE_DIRECTORY/pede 2>&1 > $PEDE_DIRECTORY/pede.log
rm $PEDE_DIRECTORY/starting$DISPLAY
touch $PEDE_DIRECTORY/stopping$DISPLAY

# put you back where you started, just in case
popd
